### ISSUE TITLE
Error bootstrapping controller: ['ERROR Get https://10.0.116.1:46783/1.0: unexpected EOF']

### ISSUE THREAD

**Issue by brettdh** [conjure-up/conjure-up#1073]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [x] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
  - Running in vSphere, so I tried turning promiscuous mode on for the vSwitch; no change
- [x] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
$ which juju
/snap/bin/juju
$ which conjure-up
/snap/bin/conjure-up
$ which conjure-up.lxd
/snap/bin/conjure-up.lxd
$ juju version
2.2.1-xenial-amd64
$ conjure-up --version
conjure-up 2.2.2
$ conjure-up.lxd --version
2.14
$ conjure-up.lxc config show
config:
  core.https_address: '[::]:46783'
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1198480/conjure-up.tar.gz)
[sosreport-bhiggins-20170803163817.tar.gz](https://github.com/conjure-up/conjure-up/files/1198587/sosreport-bhiggins-20170803163817.tar.gz)

## What Spell was Selected?

canonical-kubernetes

## What provider (aws, maas, localhost, etc)?

localhost

## Commands ran

Please outline what commands were run to install and execute conjure-up:
```
conjure-up
  --http-proxy=http://redacted.example.com:3128 
  --https-proxy=http://redacted.example.com:3128
  --apt-proxy=http://redacted.example.com:3128
  --apt-https-proxy=http://redacted.example.com:3128
```

## Additional Information

Environment is a vSphere VM; all HTTP must go through a proxy.

**Comment by Nold360** [comment]
Hi,

had the same problem.. it's really tricky, because some commands read out environment variables (like juju) but conjure-up doesn't...

The point is, it's juju reporting this, while trying to connect to the local instance using the http_proxy.
So make sure to set the environment variable "no_proxy" to at least "10.0.116.1" like this:

export no_proxy="10.0.116.1"

That should work. 


Now I try to find out, how to make LXD work behind a proxy... :/

**Comment by brettdh** [comment]
What is 10.0.116.1 though? It's not any of the host interfaces. The `conjureup0` interface (I remain confused as to why conjure-up creates a network interface) is on a different subnet. It's not the http proxy either. It seems like something that conjure-up itself is configuring, which means that conjure-up should take care of making it work with proxy settings, right?

**Comment by battlemidget** [comment]
@brettdh we create it for openstack-novalxd primarily as it needs 2 network interfaces to work

**Comment by brettdh** [comment]
Oddly, when I uninstalled and reinstalled the conjure-up snap, i now have both `conjureup0` and `conjureup1`, the latter of which has the IP that's failing with `Unexpected EOF`. I added it to `no_proxy` and got a little further, but now I see this:
```
2017-08-17 09:03:59,620 [ERROR] conjure-up/canonical-kubernetes - common.py:36 - Error bootstrapping controller: ['Creating Juju controller "conjure-up-localhost-3fd" on localhost/localhost', 'Looking for packaged Juju agent version 2.2.1 for amd64', 'To configure your system to better support LXD containers, please see: https://github.com/lxc/lxd/blob/master/doc/production-setup.md', 'Launching controller instance(s) on localhost/localhost...', '   ', ' - unable to get LXD image for juju/xenial/amd64: Get https://cloud-images.ubuntu.com/daily//streams/v1/index.json: Unable to connect to: cloud-images.ubuntu.com:443', 'ERROR failed to bootstrap model: cannot start bootstrap instance: unable to get LXD image for juju/xenial/amd64: Get https://cloud-images.ubuntu.com/daily//streams/v1/index.json: Unable to connect to: cloud-images.ubuntu.com:443']
```
like it's not using the proxy. I can `curl` the URL just fine:
```
$ curl -I -XHEAD  https://cloud-images.ubuntu.com/daily//streams/v1/index.json                                                                                                                           
HTTP/1.0 200 Connection established

HTTP/1.1 200 OK
Date: Thu, 17 Aug 2017 13:08:03 GMT
Server: Apache
Last-Modified: Thu, 17 Aug 2017 03:03:33 GMT
ETag: "234c-556ea41fd2b40"
Accept-Ranges: bytes
Content-Length: 9036
Vary: Accept-Encoding
Content-Type: application/json
```

**Comment by battlemidget** [comment]
@brettdh thanks ill take a look, we have some upcoming work this cycle to address LXD issues

**Comment by battlemidget** [comment]
Addressed in `edge` channel

**Comment by sebhoss** [comment]
I have exactly the same error with 2.3.1. Our logs show the following:

```
2017-10-12 17:56:14,322 [DEBUG] conjure-up/_unspecified_spell - app.py:237 - Juju version: 2.2.3-xenial-amd64, conjure-up version: 2.3.1
2017-10-12 17:56:14,344 [INFO] conjure-up/_unspecified_spell - events.py:171 - Watching for shutdown
2017-10-12 17:56:14,376 [DEBUG] conjure-up/_unspecified_spell - events.py:53 - Awaiting Shutdown at conjureup/events.py:174
2017-10-12 17:56:15,341 [DEBUG] conjure-up/canonical-kubernetes - download.py:60 - Path is local filesystem, copying /snap/conjure-up/745/spells/canonical-kubernetes to /home/poc/.cache/conjure-up/canonical-kubernetes
2017-10-12 17:56:15,360 [DEBUG] conjure-up/canonical-kubernetes - utils.py:406 - Pulling bundle for canonical-kubernetes from channel: stable
2017-10-12 17:56:16,647 [DEBUG] conjure-up/canonical-kubernetes - gui.py:69 - Starting watcher for verifying LXD server is available.
2017-10-12 17:56:16,648 [DEBUG] conjure-up/canonical-kubernetes - provider.py:371 - LXD query cmd: lxc query --wait -X GET /1.0
2017-10-12 17:56:16,690 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Setting LXDAvailable at conjureup/controllers/clouds/common.py:21
2017-10-12 17:56:19,470 [DEBUG] conjure-up/canonical-kubernetes - provider.py:371 - LXD query cmd: lxc query --wait -X GET /1.0/networks
2017-10-12 17:56:19,492 [DEBUG] conjure-up/canonical-kubernetes - provider.py:371 - LXD query cmd: lxc query --wait -X GET /1.0/networks/lxdbr0
2017-10-12 17:56:19,516 [DEBUG] conjure-up/canonical-kubernetes - provider.py:371 - LXD query cmd: lxc query --wait -X GET /1.0/networks/lo
2017-10-12 17:56:19,539 [DEBUG] conjure-up/canonical-kubernetes - provider.py:371 - LXD query cmd: lxc query --wait -X GET /1.0/networks/ens3
2017-10-12 17:56:19,559 [DEBUG] conjure-up/canonical-kubernetes - provider.py:371 - LXD query cmd: lxc query --wait -X GET /1.0/networks/ens8
2017-10-12 17:56:19,579 [DEBUG] conjure-up/canonical-kubernetes - provider.py:371 - LXD query cmd: lxc query --wait -X GET /1.0/storage-pools
2017-10-12 17:56:19,599 [DEBUG] conjure-up/canonical-kubernetes - provider.py:371 - LXD query cmd: lxc query --wait -X GET /1.0/storage-pools/default
2017-10-12 17:56:20,781 [DEBUG] conjure-up/canonical-kubernetes - utils.py:599 - Parsing 6: lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 1a:ab:b7:a7:bd:58 brd ff:ff:ff:ff:ff:ff
    inet 10.151.128.1/24 scope global lxdbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::18ab:b7ff:fea7:bd58/64 scope link 
       valid_lft forever preferred_lft forever
 for IPv4 address
2017-10-12 17:56:20,782 [DEBUG] conjure-up/canonical-kubernetes - gui.py:48 - LXD Info set: (name: lxdbr0) (network: 10.151.128.1/32) (gateway: 10.151.128.1) (dhcp-range-start: 10.151.128.2) (dhcp-range-stop: 10.151.128.0)
2017-10-12 17:56:23,155 [DEBUG] conjure-up/canonical-kubernetes - step.py:99 - Contents: (<Padding selectable flow widget <AttrMap selectable flow widget <PlainButton selectable flow widget 'Next'> attr_map={None: 'button_primary'} focus_map={None: 'button_primary focus'}> align='right' width=('relative', 20)>, ('weight', 1))
2017-10-12 17:56:23,168 [DEBUG] conjure-up/canonical-kubernetes - step.py:99 - Contents: (<Text flow widget ''>, ('weight', 1))
2017-10-12 17:56:24,635 [INFO] conjure-up/canonical-kubernetes - common.py:79 - Bootstrapping Juju controller.
2017-10-12 17:56:24,637 [DEBUG] conjure-up/canonical-kubernetes - juju.py:140 - Bootstrapping to set region: {}
2017-10-12 17:56:24,639 [DEBUG] conjure-up/canonical-kubernetes - juju.py:177 - bootstrap cmd: ['juju', 'bootstrap', 'localhost/localhost', 'conjure-up-localhost-d6a', '--default-model', 'conjure-canonical-kubern-fef', '--config', 'image-stream=daily', '--config', 'http-proxy=http://internal.proxy:3128', '--config', 'https-proxy=http://internal.proxy:3128', '--config', 'apt-http-proxy=http://internal.proxy:3128', '--config', 'apt-https-proxy=http://internal.proxy:3128', '--bootstrap-series', 'xenial']
2017-10-12 17:56:24,666 [DEBUG] conjure-up/canonical-kubernetes - juju.py:187 - waiting for proc
2017-10-12 17:56:26,538 [DEBUG] conjure-up/canonical-kubernetes - juju.py:189 - proc done
2017-10-12 17:56:26,538 [ERROR] conjure-up/canonical-kubernetes - common.py:54 - Error bootstrapping controller: ['Creating Juju controller "conjure-up-localhost-d6a" on localhost/localhost', 'Looking for packaged Juju agent version 2.2.3 for amd64', 'To configure your system to better support LXD containers, please see: https://github.com/lxc/lxd/blob/master/doc/production-setup.md', 'Launching controller instance(s) on localhost/localhost...', '   ', ' - unable to get LXD image for juju/xenial/amd64: Get https://cloud-images.ubuntu.com/daily//streams/v1/index.json: lookup cloud-images.ubuntu.com on [::1]:53: read udp [::1]:51412->[::1]:53: read: connection refused', 'ERROR failed to bootstrap model: cannot start bootstrap instance: unable to get LXD image for juju/xenial/amd64: Get https://cloud-images.ubuntu.com/daily//streams/v1/index.json: lookup cloud-images.ubuntu.com on [::1]:53: read udp [::1]:51412->[::1]:53: read: connection refused']
2017-10-12 17:56:26,539 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Setting Error at conjureup/events.py:147
2017-10-12 17:56:26,542 [ERROR] conjure-up/canonical-kubernetes - events.py:159 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/745/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py:16> exception=Exception('Unable to bootstrap (cloud type: localhost)',)>
Traceback (most recent call last):
  File "/snap/conjure-up/745/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 22, in run
    await self.do_bootstrap()
  File "/snap/conjure-up/745/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 57, in do_bootstrap
    app.provider.cloud_type))
Exception: Unable to bootstrap (cloud type: localhost)
2017-10-12 17:56:26,546 [DEBUG] conjure-up/canonical-kubernetes - __init__.py:21 - Showing dialog for exception: Unable to bootstrap (cloud type: localhost)
```

even though a simple curl is able to make a connection:

```
curl -I -XHEAD  https://cloud-images.ubuntu.com/daily//streams/v1/index.json  
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Date: Thu, 12 Oct 2017 16:02:29 GMT
Server: Apache
Last-Modified: Thu, 12 Oct 2017 13:38:18 GMT
ETag: "23ae-55b59a7252680"
Accept-Ranges: bytes
Content-Length: 9134
Vary: Accept-Encoding
Content-Type: application/json
```

**Comment by brettdh** [comment]
@battlemidget is there a particular commit or PR that closed this issue?

**Comment by sebhoss** [comment]
This ticket is part of the release notes for 2.3.0 (https://github.com/conjure-up/conjure-up/blob/master/CHANGELOG.md#230-2017-09-12) and I can still reproduce this issue with latest `edge` as well

**Comment by battlemidget** [comment]
@sebhoss why are you passing in proxy information if you dont need to via curl?

**Comment by battlemidget** [comment]
> @battlemidget is there a particular commit or PR that closed this issue? Or are you saying it was already resolved on edge ?

this was fixed in the edge channel and should be in the stable as well now

**Comment by sebhoss** [comment]
hey thanks for getting back to me & sorry for my late reply: I used a `export https_proxy=...` before calling curl. Without that, curl fails as well. Apart from that, I tried using `/etc/environment` to specify our proxy as well but it still fails during installs.

Another odd thing is the following (this is a fresh xenial install):
```
$ which juju
/snap/bin/juju
$ which conjure-up
/snap/bin/conjure-up
$ which conjure-up.lxd // <- odd? where do I get 'conjure-up.lxd'?
$ juju version
2.2.3-xenial-amd64
$ conjure-up --version
conjure-up 2.3.1
$ conjure-up.lxc config show
conjure-up.lxc: command not found // <- odd? likewise, where do I get 'conjure-up.lxc'?
```
