### ISSUE TITLE
Openstack spell fails on next steps

### ISSUE THREAD

**Issue by geewerx** [conjure-up/conjure-up#711]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ No ] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems
- [ Yes ] Is conjure-up running inside a virtual machine?

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

Maas server: vmware, 1 cpu, 8gb mem, 70gb storage
Juju bootstrap: vmware, 2 cpu, 6gb ram, 25gb storage
conjure-up installer: vmware, 4cpu, 6gb ram, 14gb storage
openstack server 1: vmware, 2cpu, 6gb ram, 60gb storage, 2 nic
openstack server 2: vmware, 2cpu, 6gb ram, 60gb storage
openstack server 3: vmware, 2cpu, 6gb ram, 60gb storage
openstack server 4: vmware, 2cpu, 6gb ram, 60gb storage

What spell was selected?:

openstack with NovaKVM

What cloud provider was selected (this includes both MAAS and localhost)?:

MAAS

Please outline what commands were run to install and execute conjure-up:

// tried all three of these
sudo snap install conjure-up --classic
sudo snap install conjure-up --classic --beta
sudo snap install conjure-up --classic --edge

conjure-up -d openstack

Please post **~/.cache/conjure-up/conjure-up.log**

[conjureup-log.txt](https://github.com/conjure-up/conjure-up/files/818573/conjureup-log.txt)

Provide the output of the following commands:

```
which juju
/snap/bin/juju

which conjure-up
/snap/bin/conjure-up

which lxd
/usr/bin/lxd

juju version
ubuntu@openstack-installer-1:~$ juju --version
2.1.1-xenial-amd64

conjure-up --version
ubuntu@openstack-installer-1:~$ conjure-up --version
conjure-up 2.1.2
and
ubuntu@openstack-installer-1:~$ conjure-up --version
conjure-up 2.2-dev

lxd version
ubuntu@openstack-installer-1:~$ lxd --version
2.10.1

cat /etc/lsb-release
```
ubuntu@openstack-installer-1:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

Summary of problem:

The installation of the applications completes and the next steps screen is displayed. On selecting the import glance images step, after about 30 seconds to a minute the following exception is thrown and the installation exits:

ubuntu@openstack-installer-1:~$ conjure-up -d openstack
Exception in ev.run():
Traceback (most recent call last):
  File "/snap/conjure-up/104/lib/python3.6/site-packages/ubuntui/ev.py", line 82, in run
    cls.loop.run()
  File "/snap/conjure-up/104/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/104/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/104/lib/python3.6/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'
Traceback (most recent call last):
  File "/snap/conjure-up/104/bin/conjure-up", line 11, in <module>
    sys.exit(main())
  File "/snap/conjure-up/104/lib/python3.6/site-packages/conjureup/app.py", line 362, in main
    EventLoop.run()
  File "/snap/conjure-up/104/lib/python3.6/site-packages/ubuntui/ev.py", line 82, in run
    cls.loop.run()
  File "/snap/conjure-up/104/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/104/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/104/lib/python3.6/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

I've tried this with both the beta and edge versions with the same result.

**Comment by geewerx** [comment]
[conjureup-log.txt](https://github.com/conjure-up/conjure-up/files/818573/conjureup-log.txt)

**Comment by battlemidget** [comment]
When I'm back in the office on Monday I'll take a look at this

**Comment by battlemidget** [comment]
Fixed with https://github.com/conjure-up/conjure-up/issues/504

**Comment by geewerx** [comment]
Not sure if you are saying this was fixed by or just along with #504. For the avoidance of doubt, I believe #504 was unrelated to this (other than the fact that it was being run on vmware vm's), that was just the blocker I experienced before reaching this issue.

**Comment by battlemidget** [comment]
ah ok

**Comment by kukgini** [comment]
I have same issue here. only diffrences:

- lxd version 2.11
- conjure-up version 2.1.2

**Comment by geewerx** [comment]
Apologies @battlemidget, i missed that you were asking for confirmation here. Yes, it is still an issue, although I haven't tried it since I encountered this issue 10 days ago. Happy to try again if you find a resolution.

**Comment by battlemidget** [comment]
Ok, if you guys still have the files laying around could you attach a tarball of `~/.cache/conjure-up`? I believe this is an error within the spell itself and need to check that debug output.

**Comment by battlemidget** [comment]
closing this as we can't reproduce it in our lab. If you are able to reproduce and capture the log files please reopen
